# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(355, 419)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/Calculator_512.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calculator.setWindowIcon(icon)
        Calculator.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 213, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 1, 0, 1, 2)
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        self.push_8.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_8.setObjectName("push_8")
        self.gridLayout.addWidget(self.push_8, 4, 1, 1, 1)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        self.push_6.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_6.setObjectName("push_6")
        self.gridLayout.addWidget(self.push_6, 3, 2, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        self.push_7.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_7.setObjectName("push_7")
        self.gridLayout.addWidget(self.push_7, 4, 0, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        self.push_9.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_9.setObjectName("push_9")
        self.gridLayout.addWidget(self.push_9, 4, 2, 1, 1)
        self.push_00 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_00.sizePolicy().hasHeightForWidth())
        self.push_00.setSizePolicy(sizePolicy)
        self.push_00.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_00.setObjectName("push_00")
        self.gridLayout.addWidget(self.push_00, 5, 0, 1, 1)
        self.push_dot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_dot.sizePolicy().hasHeightForWidth())
        self.push_dot.setSizePolicy(sizePolicy)
        self.push_dot.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_dot.setObjectName("push_dot")
        self.gridLayout.addWidget(self.push_dot, 5, 2, 1, 1)
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_0.sizePolicy().hasHeightForWidth())
        self.push_0.setSizePolicy(sizePolicy)
        self.push_0.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_0.setObjectName("push_0")
        self.gridLayout.addWidget(self.push_0, 5, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 213, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    ;\n"
"    background-color: rgb(255, 52, 52);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 213, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 4, 3, 1, 1)
        self.push_equle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_equle.sizePolicy().hasHeightForWidth())
        self.push_equle.setSizePolicy(sizePolicy)
        self.push_equle.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 213, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.push_equle.setObjectName("push_equle")
        self.gridLayout.addWidget(self.push_equle, 5, 3, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 213, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 33pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_1.setObjectName("push_1")
        self.gridLayout.addWidget(self.push_1, 2, 0, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_3.setObjectName("push_3")
        self.gridLayout.addWidget(self.push_3, 2, 2, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_4.setObjectName("push_4")
        self.gridLayout.addWidget(self.push_4, 3, 0, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_2.setObjectName("push_2")
        self.gridLayout.addWidget(self.push_2, 2, 1, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        self.push_5.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(111, 111, 111);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(168, 168, 168);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 111, 111);\n"
"}")
        self.push_5.setObjectName("push_5")
        self.gridLayout.addWidget(self.push_5, 3, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 213, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.pushButton_16.setText(_translate("Calculator", "C"))
        self.pushButton_16.setShortcut(_translate("Calculator", "Backspace"))
        self.push_8.setText(_translate("Calculator", "8"))
        self.push_8.setShortcut(_translate("Calculator", "8"))
        self.push_6.setText(_translate("Calculator", "6"))
        self.push_6.setShortcut(_translate("Calculator", "6"))
        self.push_7.setText(_translate("Calculator", "7"))
        self.push_7.setShortcut(_translate("Calculator", "7"))
        self.push_9.setText(_translate("Calculator", "9"))
        self.push_9.setShortcut(_translate("Calculator", "9"))
        self.push_00.setText(_translate("Calculator", "00"))
        self.push_00.setShortcut(_translate("Calculator", "0, 0"))
        self.push_dot.setText(_translate("Calculator", "."))
        self.push_dot.setShortcut(_translate("Calculator", "."))
        self.push_0.setText(_translate("Calculator", "0"))
        self.push_0.setShortcut(_translate("Calculator", "0"))
        self.pushButton_13.setText(_translate("Calculator", "-"))
        self.pushButton_13.setShortcut(_translate("Calculator", "-"))
        self.pushButton_17.setText(_translate("Calculator", "Del"))
        self.pushButton_17.setShortcut(_translate("Calculator", "Del"))
        self.pushButton_14.setText(_translate("Calculator", "÷"))
        self.pushButton_14.setShortcut(_translate("Calculator", "/"))
        self.push_equle.setText(_translate("Calculator", "="))
        self.push_equle.setShortcut(_translate("Calculator", "Enter"))
        self.pushButton_18.setText(_translate("Calculator", "x"))
        self.pushButton_18.setShortcut(_translate("Calculator", "*"))
        self.push_1.setText(_translate("Calculator", "1"))
        self.push_1.setShortcut(_translate("Calculator", "1"))
        self.push_3.setText(_translate("Calculator", "3"))
        self.push_3.setShortcut(_translate("Calculator", "3"))
        self.push_4.setText(_translate("Calculator", "4"))
        self.push_4.setShortcut(_translate("Calculator", "4"))
        self.push_2.setText(_translate("Calculator", "2"))
        self.push_2.setShortcut(_translate("Calculator", "2"))
        self.push_5.setText(_translate("Calculator", "5"))
        self.push_5.setShortcut(_translate("Calculator", "5"))
        self.pushButton_12.setText(_translate("Calculator", "+"))
        self.pushButton_12.setShortcut(_translate("Calculator", "+"))

        self.push_1.clicked.connect(self.method_1)
        self.push_2.clicked.connect(self.method_2)
        self.push_3.clicked.connect(self.method_3)
        self.push_4.clicked.connect(self.method_4)
        self.push_5.clicked.connect(self.method_5)
        self.push_6.clicked.connect(self.method_6)
        self.push_7.clicked.connect(self.method_7)
        self.push_8.clicked.connect(self.method_8)
        self.push_9.clicked.connect(self.method_9)
        self.push_0.clicked.connect(self.method_zero)
        self.push_dot.clicked.connect(self.method_dot)
        self.push_00.clicked.connect(self.method_duble_zero)
        self.pushButton_13.clicked.connect(self.method_subtract)
        self.pushButton_16.clicked.connect(self.method_clear)
        self.pushButton_17.clicked.connect(self.method_del)
        self.pushButton_18.clicked.connect(self.method_multiply)
        self.pushButton_12.clicked.connect(self.method_plus)
        self.pushButton_14.clicked.connect(self.method_divide)
        self.push_equle.clicked.connect(self.method_equle)


    def method_1(self):
        text=self.label.text()
        self.label.setText(text+"1")
    def method_2(self):
        text=self.label.text()
        self.label.setText(text+"2")
    def method_3(self):
        text=self.label.text()
        self.label.setText(text+"3")
    def method_4(self):
        text=self.label.text()
        self.label.setText(text+"4")
    def method_5(self):
        text=self.label.text()
        self.label.setText(text+"5")
    def method_6(self):
        text=self.label.text()
        self.label.setText(text+"6")
    def method_7(self):
        text=self.label.text()
        self.label.setText(text+"7")
    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")
    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
    def method_zero(self):
        text=self.label.text()
        self.label.setText(text+"0")
    def method_plus(self):
        text=self.label.text()
        self.label.setText(text+"+")
    def method_subtract(self):
        text=self.label.text()
        self.label.setText(text+"-")
    def method_multiply(self):
        text=self.label.text()
        self.label.setText(text+"*")
    def method_divide(self):
        text=self.label.text()
        self.label.setText(text+"/")
    def method_dot(self):
        text=self.label.text()
        self.label.setText(text+".")
    def method_clear(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-1])
    def method_del(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-100000000])
    def method_duble_zero(self):
        text=self.label.text()
        self.label.setText(text+"00")
    def method_equle(self):
        text=self.label.text()
        try:
            ans=eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("wrong Input")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
